version: '3.8'
services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8082

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  webservice:
    build: ./webservice
    container_name: webservice
    ports:
      - "8084:8084"
    volumes:
      - ./webservice:/app
    depends_on:
      - rabbitmq
      - db

  account:
    build: ./account
    container_name: account
    ports:
      - "8080:8080"
    volumes:
      - ./account:/app
    depends_on:
      - rabbitmq
      - db
      - webservice

  transaction:
    build: ./transaction
    container_name: transaction
    ports:
      - "8081:8081"
    volumes:
      - ./transaction:/app
    depends_on:
      - account
      - rabbitmq
      - db
      - webservice
volumes:
      db:
        driver: local